Remove utils/run_tests.sh
* Remove the utils/run_tests.sh as it is renamed to colibri_build_test.sh
* Remove -- bulk_if.c:962: error: ‘to_before’ may be used uninitialized in this function
  by initialinzing the variable to 0