configure.ac: large segment size configuration fixed
--with-segment-size=8192 configuration caused the following:
db/db.c:73: error: integer overflow in expression

Change-Id: Idd6bce0b4c157ea40347e413a2209bccb21f20bf