lib/trace UT: Fix large stack frame
    lib/ut/trace.c:test_trace() allocates struct c2_thread t[NR] on stack. This
    array is more than 1.2KB, which is bad for kernel:

  CC [M]  colibri/core/build_kernel_modules/lib/ut/trace.o

colibri/core/build_kernel_modules/lib/ut/trace.c: In function 'test_trace':
colibri/core/build_kernel_modules/lib/ut/trace.c:66:1: error: the frame size of 1264 bytes is larger than 1024 bytes [-Werror=frame-larger-than=]

    Make this array static.