m0t1fs: add CPU usage threshold for parity calcs
When a large number of I/O process is started, all CPUs
may be used for parity calculations and cause starvation
for LNet threads. That consequently may cause LNet to
generate timeout errors for RDMA transfers:

LNetError: 32682:0:(o2iblnd_cb.c:3012:kiblnd_check_txs_locked()) Timed out tx: active_txs, 3 seconds
LNetError: 32682:0:(o2iblnd_cb.c:3075:kiblnd_check_conns()) Timed out RDMA with 172.18.1.11@o2ib (53): c: 0, oc: 1, rc: 0

that ends up with I/O failures.

To avoid these problems we introduce the CPUs usage
threshold for parity calculation threads by adding
the global semaphore and initializing it with number
of 50 percent of available online CPUs in the system.
Tests shows that it is optimal trade-off number when we
don't see the errors already from one side and yet there
is still good throughput from another side.

This change fixes MERO-449 issue.

Reviewed-by: Nikita Danilov <nikita.danilov@seagate.com>
References: https://jira.xyratex.com/browse/MERO-449

Change-Id: I8808ab83d5045a991fcd794ba26b91ac42b250a4