m0genfacts (collect_disks_for): deal with NIL
collect_disks_for(): `disk_string' may be NIL. Instead of spooking users
with cryptic error message, handle NIL.

Before:

  /data/src/mero/utils/m0genfacts:458:in `collect_disks_for': undefined method `strip' for nil:NilClass (NoMethodError)
          from /data/src/mero/utils/m0genfacts:614:in `block in <main>'
          from /data/src/mero/utils/m0genfacts:608:in `each'
          from /data/src/mero/utils/m0genfacts:608:in `<main>'

After:

  m0genfacts: ERROR: [cmu.local]: failed to find disks matching pattern '/dev/sdb'

Change-Id: I6eec4bfbba0a7b99558198f9049b9b8fc8fac4d3