build: centos7: gcc4.8: fix -Werror=unused-but-set-variable warning
Change-Id: Ic082bf1eae2b241bfbaa484e66ef0873bac8f592
DEBUG: stob/ad.c: In function 'ext_destroy':
DEBUG: stob/ad.c:690:20: error: variable 'prefix' set but not used [-Werror=unused-but-set-variable]
DEBUG:   struct m0_uint128         prefix;
DEBUG:                     ^
DEBUG: cc1: all warnings being treated as errors