build: centos7: gcc4.8: fix -Wunused-but-set-variable warnings
Fix series of warnings, which appears when using gcc 4.8:

/data/prj/mero/addb/user_space/addb_retrieval.c: In function 'stob_segment_iter_next':
/data/prj/mero/addb/user_space/addb_retrieval.c:318:29: error: variable
'dom' set but not used [-Werror=unused-but-set-variable]
  struct m0_stob_domain     *dom;
                               ^

Change-Id: Ib1dd9df98ae5130f22c8bdae3f2065d8042f53b8