lustre_hsm: Mero build fails for lustre version 2.6.51
`ct_run': m0lhsmtool.c:(.text+0x4eaa): undefined reference to `llapi_hsm_action_list_free'

* This was changed in following lustre commit,
>>>>
commit 76dca841869d87df2b625cb9d186d531c406fc9b
Author: Frank Zago <fzago@cray.com>
Date:   Thu May 22 13:27:56 2014 -0500

   LU-5051 hsm: do not reallocate hsm receive buffer

   Instead of allocating 1MB for every call to
   llapi_hsm_copytool_recv, allocate that buffer once in
   llapi_hsm_copytool_register. The application must not call
   llapi_hsm_copytool_recv until it has cleared the data from
   the previous call, which lhsmtool_posix already does. This
   also make llapi_hsm_action_list_free unnecessary.
>>>>

* Currently fix the build issue by invoking llapi_hsm_action_list_free() iff
  lustre version < 2.6.51

Change-Id: I38737d4763d0e0417603885d39cd9929bd99008a