be/btree: remove inline keyword from invariant
Remove inline keyword from btree_node_invariant() because it causes
compilation error:
    be/btree.c:244:20: error: inlining failed in call to always_inline
    'btree_node_invariant': recursive inlining

Change-Id: Ie21df131d0c7b4e276c8539a3d7501040f98e132