build: centos7: gcc4.8: fix error '_Static_assert argument is not a constant'
Was not able to come up with a better alternative, so simply removed the
offending line. It seems to be harmless.. Originally, it caused the
following error:

   CC       stob/mero_libmero_la-linux.lo
 In file included from /home/devvm/mero/lib/linux_kernel/types.h:28:0,
                  from /home/devvm/mero/lib/types.h:27,
                  from /home/devvm/mero/addb/addb.h:30,
                  from /home/devvm/mero/fop/fop_addb.h:26,
                  from /home/devvm/mero/fop/fop.c:25:
 /home/devvm/mero/lib/assert.h:243:42: error: expression in static assertion is not constant
  # define M0_BASSERT(cond) _Static_assert((cond), #cond)
                                           ^
 /home/devvm/mero/addb/addb.h:296:1: note: in expansion of macro ‘M0_BASSERT’
  M0_BASSERT((smconf) != NULL);     \
  ^
 /home/devvm/mero/fop/fop_addb.h:125:1: note: in expansion of macro ‘M0_ADDB_RT_SM_CNTR’
  M0_ADDB_RT_SM_CNTR(m0_addb_rt_fom_state_stats, M0_ADDB_RECID_FOM_STATE_STATS,
  ^

Change-Id: If99279c8f43d59ed8bb25ccf2c155346d799d222