fix build errors in release mode with gcc-4.6
Fix error which are reported by gcc-4.6 when building in release mode
(i.e. ./configure --disable-debug and gcc -O2):

    processor.c:207:3: error: 'pbitmap' may be used uninitialized in this function [-Werror=uninitialized]
    processor.c:948:8: error: ignoring return value of 'chdir', declared with attribute warn_unused_result [-Werror=unused-result]

Reviewed-on: http://reviewboard.clusterstor.com/r/777
Reviewed-by: Huang Hua <hua_huang@xyratex.com>