be: ensure that index is within array boundaries
Add a precondition to be_tx_ast_cb() and be_tx_ast().

The change to `be_tx_ast_offset' definition fixes sporadic compilation error,
which manifests itself in one of the development branches
(see https://seagate.slack.com/archives/mero/p1403775885000263):

| $ m0 rebuild
| ...skip...
|   CC     sns/cm/st/mero_libmero_la-repair_cli.lo
|   CCLD   mero/libmero.la
|   CC     mero/mero_libmero_altogether_la-mero_altogether_user.lo
| cc1: warnings being treated as errors
| In file included from mero/mero_altogether_user.c:23:
| /mnt/hgfs/vvv/src/mero/be/tx_group.c: In function ‘m0_be_tx_group__tx_state_post’:
| /mnt/hgfs/vvv/src/mero/be/tx.c:84: error: array subscript is above array bounds
| /mnt/hgfs/vvv/src/mero/be/tx.c:84: error: array subscript is above array bounds
| make[2]: *** [mero/mero_libmero_altogether_la-mero_altogether_user.lo] Error 1
| make[1]: *** [all-recursive] Error 1
| make: *** [all] Error 2

Change-Id: I13f8baa768a37f3fdb59d210c2e4a62a2dbc29aa