rm: fix build dependency of rm.h on *_xc.h files
If some .h file includes *_xc.h files, they should be specified as
dependencies for such .h file in Makefile.sub. Otherwise, build time
error will occur, like the following one, which is fixed by this patch:

    GCCXML  rm/rm_xc.h
    rm/rm.h:32:27: error: lib/cookie_xc.h: No such file or directory
    make: *** [rm/rm_xc.h] Error 1