fix build errors in release mode with gcc-4.4
Fix errors which are reported by gcc-4.4 when building in release mode
(i.e. ./configure --disable-debug and gcc -O2):

    processor.c:207:3: error: 'pbitmap' may be used uninitialized in this function [-Werror=uninitialized]

Reviewed-on: http://reviewboard.clusterstor.com/r/777
Reviewed-by: Huang Hua <hua_huang@xyratex.com>