Makefile.am: fix build error due to dependency on fid_xc.h
The commit t1.4-s20-899-g44837a8 "Use the same fid and fid_xc structure
everywhere" uses wrong approach to fix build error, which happens due to
dependency of conf/onwire.h on fid/fid_xc.h:

    $ make
    Checking source files... OK
     GCCXML  lib/buf_xc.h
     GCCXML2XC  lib/buf_xc.h
     GCCXML  conf/onwire_xc.h
    conf/onwire.h:28:24: error: fid/fid_xc.h: No such file or directory
    make: *** [conf/onwire_xc.h] Error 1

The right way to resolve it is to explicitly specify fid_xc.h as a
prerequisite for onwire.h in Makefile. The same should be done for other
.h files, which include fid_xc.h.