Changes to make `make dist' work.
* Add missing files to Makefile.am
* cs_ut_main.c:342: error: ignoring return value of 'system',
  declared with attribute warn_unused_result
  Assert the return value