build: fix errors when building with CFLAGS='-Wp,-D_FORTIFY_SOURCE=2'
Xyratex SL6 distributions use non standard version of redhat-rpm-config
package, which provides tweaks for CFLAGS in /usr/lib/rpm/redhat/macros
file. Specifically, it adds -Wp,-D_FORTIFY_SOURCE=2 option to CFLAGS,
which causes series of build errors like:

      CC     lib/user_space/mero_libmero_la-processor.lo
    cc1: warnings being treated as errors
    lib/user_space/processor.c: In function ‘processors_summary_get’:
    lib/user_space/processor.c:818: error: ignoring return value of ‘chdir’, declared with attribute warn_unused_result

This didn't allow to build Mero rpm package on hosts with installed
xyratex's redhat-rpm-config package. To fix it, this patch adds checks
of return values for system funcs which require it.