lustre_hsm: revert commit 'lib/trace: wrap plain "return -EXXX" into M0_ERR'
m0lhsmtool is a standalone utility which is not linked with libmero.so,
so it doesn't make sense to use M0_ERR() in it's code. It was an
oversight and this patch reverts commit d6219097a9a39446960ce0ac6d2da25ce8f50ba2
'lib/trace: wrap plain "return -EXXX" into M0_ERR' for lustre_hsm/m0lhsmtool.c file.

This fixes build error, when building Mero with Lustre version >= 2.5:

   CC     lustre_hsm/lustre_hsm_m0lhsmtool-m0lhsmtool.o
  In file included from /mnt/madhav/MASTER/mero-aa/mero/fid/fid.h:33,
                   from lustre_hsm/m0lhsmtool.c:49:
  /mnt/madhav/MASTER/mero-aa/mero/lib/types.h:36: warning: ‘gccxml’ attribute directive ignored
  In file included from lustre_hsm/m0lhsmtool.c:49:
  /mnt/madhav/MASTER/mero-aa/mero/fid/fid.h:39: warning: ‘gccxml’ attribute directive ignored
    CCLD   lustre_hsm/m0lhsmtool
  lustre_hsm/lustre_hsm_m0lhsmtool-m0lhsmtool.o: In function `ct_parseopts':
  m0lhsmtool.c:(.text+0x468): undefined reference to `M0_ERR'
  lustre_hsm/lustre_hsm_m0lhsmtool-m0lhsmtool.o: In function `ct_load_stripe':
  m0lhsmtool.c:(.text+0xcf0): undefined reference to `M0_ERR'
  m0lhsmtool.c:(.text+0xd84): undefined reference to `M0_ERR'
  lustre_hsm/lustre_hsm_m0lhsmtool-m0lhsmtool.o: In function `ct_copy_data':
  m0lhsmtool.c:(.text+0x1119): undefined reference to `M0_ERR'
  lustre_hsm/lustre_hsm_m0lhsmtool-m0lhsmtool.o: In function `ct_process_item_async':
  m0lhsmtool.c:(.text+0x370d): undefined reference to `M0_ERR'
  lustre_hsm/lustre_hsm_m0lhsmtool-m0lhsmtool.o:m0lhsmtool.c:(.text+0x3755): more undefined references to `M0_ERR' follow

Change-Id: I0d3a9d406ea9c4c8ad8e59224a02b021572e7a44
Reported-by: Madhav Vemuri <madhav.vemuri@seagate.com>