build: fix gccxml errors while processing finject.h
Fix the following build error, reported by gccxml, when it tries to
process some header file, which includes lib/finject.h:

  GCCXML     addb/addb_fops_xc.h
  In file included from /home/xyratex/proj/mero_master/be/alloc.h:27,
                   from /home/xyratex/proj/mero_master/be/seg.h:25,
                   from /home/xyratex/proj/mero_master/be/tx_regmap.h:25,
                   from /home/xyratex/proj/mero_master/be/tx.h:27,
                   from /home/xyratex/proj/mero_master/be/op.h:26,
                   from /home/xyratex/proj/mero_master/be/be.h:25,
                   from /home/xyratex/proj/mero_master/be/btree.h:24,
                   from /home/xyratex/proj/mero_master/fol/fol.h:107,
                   from /home/xyratex/proj/mero_master/fop/fop.h:31,
                   from addb/addb_fops.h:26:
  /home/xyratex/proj/mero_master/lib/finject.h: In function 'void m0_fi_enable(const char*, const char*)':
  /home/xyratex/proj/mero_master/lib/finject.h:276: error: expected primary-expression before 'const'
  /home/xyratex/proj/mero_master/lib/finject.h:276: error: expected `)' before 'const'
  /home/xyratex/proj/mero_master/lib/finject.h: In function 'void m0_fi_enable_once(const char*, const char*)':
  /home/xyratex/proj/mero_master/lib/finject.h:291: error: expected primary-expression before 'const'
  /home/xyratex/proj/mero_master/lib/finject.h:291: error: expected `)' before 'const'
  /home/xyratex/proj/mero_master/lib/finject.h: In function 'void m0_fi_enable_random(const char*, const char*, uint32_t)':
  /home/xyratex/proj/mero_master/lib/finject.h:309: error: expected primary-expression before 'const'
  /home/xyratex/proj/mero_master/lib/finject.h:309: error: expected `)' before 'const'
  addb/addb_fops.h:65: error: expected `;' at end of input
  addb/addb_fops.h:65: error: expected `}' at end of input
  make[1]: *** [addb/addb_fops_xc.h] Error 1

It happend because of a special C syntax, used in finject.h. Since gccxml is
essentially a C++ compiler, it doesn't support C99 compound literals and
designated initializers. So we want to hide this fancy code from gccxml to
protect it from brain damage :D It's safe, because we are interested only in
type definition information, produced by gccxml, and not a function
implementation.