build: centos7: gcc4.8: fix -Werror=unused-result warning.
Fix warning, which appears when using gcc 4.8:
rpc/it/rpc_ping.c: In function 'quit_dialog':
rpc/it/rpc_ping.c:398:6: error: ignoring return value of 'read', declared with attribute warn_unused_result [-Werror=unused-result]
  read(0, &ch, sizeof ch);

Change-Id: Ibee5793b0196d143e6134a6f14367c34ff493fa